import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import axios from "axios";

import { fetchProducts } from "../App/Features/productSlice";
import { fetchCategory } from "../App/Features/categorySlice";
import { selectProducts } from "../App/Features/productSlice";
import { selectCategory } from "../App/Features/categorySlice";

import styles from "../styles/Home.module.scss";
import model from "./assets/model.jpg";
import sofa from "./assets/fur12.jpg";

import Carousal from "../components/Carousal";
import CategoriesCard from "../components/CategoriesCard";
import DiscountCard from "../components/DiscountCard";
import cardimage from "../components/assets/fur12.jpg";
import catchair from "../components/assets/chair3.png";
import BannerCard from "../components/BannerCard";
import CategoryCard from "../components/CategoryCard";
import ThinBannerCard from "../components/ThinBannerCard";

export default function Home() {
  const [slider, setSlider] = useState([]);
  const dispatch = useDispatch();
  const products = useSelector(selectProducts);
  const categories = useSelector(selectCategory);

  const mainCategories = categories?.categories.filter((cat) => {
    return cat.parent_id === "";
  });

  useEffect(() => {
    dispatch(fetchCategory());
    dispatch(fetchProducts());
  }, [dispatch]);


  useEffect(() => {
    async function getSLider() {
      try {
        const response = await axios.get(
          "https://ashley-api.herokuapp.com/sliders"
        );
        // console.log(response);
        setSlider(response.data.sliders);
      } catch (error) {
        console.error(error);
      }
    }
    getSLider();
    console.log(mainCategories)
  }, []);

  return (
    <div className="index_wrapper">
      <Head>
        <title>Furniture ECommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home_wrapper}>
        <Carousal
          height={460}
          slider={slider}
          url="https://ashley-api.herokuapp.com/uploads/slider/"
        />
        <div className={styles.discount_cards_wrapper}>
          <div className={styles.discount_cards_heading}>
            <h2>Discount in full bloom</h2>
          </div>
          <div className={styles.discount_cards}>
            <DiscountCard img={cardimage} />
            <DiscountCard img={cardimage} />
            <DiscountCard img={cardimage} />
          </div>
          <div className={styles.discount_cards}>
            <DiscountCard img={cardimage} />
            <DiscountCard img={cardimage} />
            <DiscountCard img={cardimage} />
          </div>
        </div>
        <div className={styles.categories_wrapper}>
          <h3>Shop By Categories</h3>
          <div className={styles.categories}>
            {categories?.categories?.slice(0, 6).map((category) => (
              <CategoriesCard
                key={category._id}
                img={category.image ? category.image : catchair}
                title={category.title}
              />
            ))}
          </div>
          <div className={styles.categories}>
            {categories?.categories?.slice(6, 12).map((category) => (
              <CategoriesCard
                key={category._id}
                img={category.image ? category.image : catchair}
                title={category.title}
              />
            ))}
          </div>
        </div>
        <div className={styles.banner_card_wrapper}>
          <BannerCard
            img={model}
            cat="Category"
            title="Title"
            feature="This is the features of the product"
          />
        </div>
        <div className={styles.category_cards}>
          <CategoryCard
            img={sofa}
            title="Something"
            feature="something under something"
          />
          <CategoryCard
            img={sofa}
            title="Something"
            feature="something under something"
          />
          <CategoryCard
            img={sofa}
            title="Something"
            feature="something under something"
          />
          <CategoryCard
            img={sofa}
            title="Something"
            feature="something under something"
          />
        </div>
        <div className={styles.free_shipping}>
          <h4>Swith it up</h4>
          <h2>Update your happy Place</h2>
          <div className={styles.category_cards}>
            <CategoryCard
              img={sofa}
              title="Something"
              feature="something under something"
            />
            <CategoryCard
              img={sofa}
              title="Something"
              feature="something under something"
            />
            <CategoryCard
              img={sofa}
              title="Something"
              feature="something under something"
            />
          </div>
        </div>
        <div className={styles.thin_banner_wrapper}>
          <ThinBannerCard title="outdoor" feature="reintroducing" />
        </div>
        <div className={styles.free_shipping}>
          <h4>Swith it up</h4>
          <h2>Update your happy Place</h2>
          <div className={styles.category_cards}>
            <CategoryCard
              img={sofa}
              title="Something"
              feature="something under something"
            />
            <CategoryCard
              img={sofa}
              title="Something"
              feature="something under something"
            />
            <CategoryCard
              img={sofa}
              title="Something"
              feature="something under something"
            />
          </div>
        </div>

        <div className={styles.thin_banner_wrapper}>
          <ThinBannerCard title="outdoor" feature="reintroducing" />
        </div>
      </div>
    </div>
  );
}
